

name: trigger gitlab job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: "http://gitlab.com"
        token: 957f5ebce6cf4b2a12d1512804e00f
        project_id: 22925079
          
